-- question 1 from homework

-- create the films struct
-- CREATE TYPE films AS (
-- 	film TEXT,
-- 	year INTEGER, -- included this because i wanted to
-- 	votes INTEGER,
-- 	rating REAL,
-- 	filmid TEXT
-- )

-- create the quality_class. used enum to enforce categories
-- CREATE TYPE quality_class AS ENUM ('star', 'good', 'average', 'bad')

-- create the actors table
-- CREATE TABLE actors (
-- 	actor TEXT,
-- 	actorid TEXT,
-- 	films films[],
-- 	quality_class quality_class,
-- 	is_active BOOLEAN,
-- 	current_year INTEGER,
-- 	PRIMARY KEY(actorid, current_year)
-- )


-- question 2 from homework

-- using this query, i determined min year is 1970. 1969 is seed query
-- SELECT MIN(year) FROM actor_films

-- i also found out the max year is 2021

-- code I used to populate actors table
-- INSERT INTO actors
-- WITH ly AS (
-- 	SELECT *
-- 	FROM actors
-- 	WHERE current_year = 1974
-- ),
-- cy AS (
-- 	SELECT
-- 		actor,
-- 		actorid,
-- 		year,
-- 		ARRAY_AGG(ROW(film, year, votes, rating, filmid)::films) AS films,
-- 		CASE -- order matters here!
-- 			WHEN avg(rating) > 8 THEN 'star'
-- 			WHEN avg(rating) > 7 THEN 'good'
-- 			WHEN avg(rating) > 6 THEN 'average'
-- 			WHEN avg(rating) <= 6 THEN 'bad' -- coding this in for quality insurance vs having as else stmt
-- 		END::quality_class
-- 	FROM actor_films
-- 	WHERE year = 1975
-- 	GROUP BY actor, actorid, year
-- ),
-- combined AS (
-- 	SELECT
-- 		COALESCE(cy.actor, ly.actor) AS actor,
-- 		COALESCE(cy.actorid, ly.actorid) AS actorid,
-- 		CASE
-- 			WHEN ly.films IS NULL THEN cy.films
-- 			WHEN CY.films IS NOT NULL THEN ly.films || cy.films
-- 			ELSE ly.films
-- 		END AS films,
-- 		COALESCE(cy.quality_class, ly.quality_class) AS quality_class,
-- 		CASE
-- 			WHEN cy.year IS NOT NULL THEN TRUE ELSE FALSE
-- 		END AS is_active,
-- 		COALESCE(cy.year, ly.current_year + 1) AS current_year
-- 	FROM ly
-- 	FULL OUTER JOIN cy
-- 		ON ly.actorid = cy.actorid
-- )
-- SELECT * FROM combined


-- question 3
-- CREATE TABLE actors_history_scd (
-- 	actor TEXT,
-- 	actorid TEXT,
-- 	quality_class quality_class,
-- 	is_active BOOLEAN,
-- 	start_year INTEGER,
-- 	end_year INTEGER,
-- 	current_year INTEGER,
-- 	PRIMARY KEY (actorid, start_year)
-- )

-- question 4
-- WITH raw_actors AS (
-- 	SELECT
-- 		*,
-- 		LAG(quality_class, 1) OVER (PARTITION BY actorid ORDER BY current_year) as prev_quality,
-- 		LAG(is_active, 1) OVER (PARTITION BY actorid ORDER BY current_year) as prev_is_active
-- 	FROM actors
-- ),
-- indicators AS (
-- 	SELECT
-- 		*,
-- 		CASE
-- 			WHEN quality_class <> prev_quality THEN 1
-- 			WHEN is_active <> prev_is_active THEN 1
-- 			ELSE 0
-- 		END AS change_indicator
-- 	FROM raw_actors
-- ),
-- streaks AS (
-- SELECT
-- 	*,
-- 	SUM(change_indicator) OVER (PARTITION BY actorid ORDER BY current_year) AS streak_identifier
-- FROM indicators
-- )
-- SELECT
-- 	actor,
-- 	actorid,
-- 	quality_class,
-- 	is_active,
-- 	MIN(current_year) AS start_season,
-- 	MAX(current_year) AS end_season,
-- 	1975 AS current_year
-- FROM streaks
-- GROUP BY actor, actorid, quality_class, is_active, streak_identifier
-- ORDER BY actor


-- question 5
-- INSERT INTO actors_history_scd
-- WITH raw_actors AS (
-- 	SELECT
-- 		*,
-- 		LAG(quality_class, 1) OVER (PARTITION BY actorid ORDER BY current_year) as prev_quality,
-- 		LAG(is_active, 1) OVER (PARTITION BY actorid ORDER BY current_year) as prev_is_active
-- 	FROM actors
-- 	WHERE current_year < 1975 -- manually filtering here knowing our data goes up to 1975
-- ),
-- indicators AS (
-- 	SELECT
-- 		*,
-- 		CASE
-- 			WHEN quality_class <> prev_quality THEN 1
-- 			WHEN is_active <> prev_is_active THEN 1
-- 			ELSE 0
-- 		END AS change_indicator
-- 	FROM raw_actors
-- ),
-- streaks AS (
-- SELECT
-- 	*,
-- 	SUM(change_indicator) OVER (PARTITION BY actorid ORDER BY current_year) AS streak_identifier
-- FROM indicators
-- )
-- SELECT
-- 	actor,
-- 	actorid,
-- 	quality_class,
-- 	is_active,
-- 	MIN(current_year) AS start_season,
-- 	MAX(current_year) AS end_season,
-- 	1974 AS current_year
-- FROM streaks
-- GROUP BY actor, actorid, quality_class, is_active, streak_identifier
-- ORDER BY actor

-- SELECT * FROM actors_history_scd

-- SELECT * FROM actors WHERE actor = 'Donald Sutherland'
-- SELECT * FROM actors_history_scd WHERE actor = 'Donald Sutherland' order by start_year
-- SELECT * FROM actors where actor = 'Donald Sutherland'

-- CREATE TYPE scd_type AS (
-- 	quality_class quality_class,
-- 	is_active BOOLEAN,
-- 	start_year INTEGER,
-- 	end_year INTEGER
-- )

-- WITH ly_scd AS (
-- 	SELECT
-- 		*
-- 	FROM actors_history_scd
-- 	WHERE actor = 'Donald Sutherland'
-- 		AND end_year = 1974
-- ),
-- historical_scd AS (
-- 	SELECT
-- 		actor,
-- 		actorid,
-- 		quality_class,
-- 		is_active,
-- 		start_year,
-- 		end_year,
-- 		1975 AS current_year
-- 	FROM actors_history_scd
-- 	WHERE actor = 'Donald Sutherland'
-- 		AND end_year < 1974
-- ),
-- cy_actors AS (
-- 	SELECT
-- 		*
-- 	FROM actors
-- 	WHERE actor = 'Donald Sutherland'
-- 		AND current_year = 1975
-- ),
-- unchanged_records AS (
-- 	SELECT
-- 		cy.actor,
-- 		cy.actorid,
-- 		cy.quality_class,
-- 		cy.is_active,
-- 		ly.start_year,
-- 		cy.current_year AS end_year,
-- 		1975 AS current_year
-- 	FROM ly_scd ly
-- 	JOIN cy_actors cy
-- 		ON ly.actorid = cy.actorid
-- 	WHERE ly.quality_class = cy.quality_class
-- 		AND ly.is_active = cy.is_active
-- ),
-- changed_records AS (
-- 	SELECT
-- 		cy.actor,
-- 		cy.actorid,
-- 		UNNEST(ARRAY[
-- 			ROW(
-- 				ly.quality_class,
-- 				ly.is_active,
-- 				ly.start_year,
-- 				ly.end_year
-- 			)::scd_type,
-- 			ROW(
-- 				cy.quality_class,
-- 				cy.is_active,
-- 				cy.current_year,
-- 				cy.current_year
-- 			)::scd_type
-- 		]) as arr,
-- 		1975 as current_year
-- 	FROM cy_actors cy
-- 	LEFT JOIN ly_scd ly
-- 		ON ly.actorid = cy.actorid
-- 	WHERE ly.quality_class <> cy.quality_class
-- 		OR ly.is_active <> cy.is_active
-- ),
-- unnested_changed_records AS (
-- 	SELECT
-- 		actor,
-- 		actorid,
-- 		(arr::scd_type).*,
-- 		current_year
-- 	FROM changed_records
-- ),
-- new_records AS (
-- 	SELECT
-- 		cy.actor,
-- 		cy.actorid,
-- 		cy.quality_class,
-- 		cy.is_active,
-- 		cy.current_year AS start_year,
-- 		cy.current_year AS end_year,
-- 		1975 AS current_year
-- 	FROM cy_actors cy 
-- 	LEFT JOIN ly_scd ly
-- 		ON ly.actorid = cy.actorid
-- 	WHERE ly.actor IS NULL
-- )
-- SELECT * FROM historical_scd
-- UNION ALL
-- SELECT * FROM unchanged_records
-- UNION ALL
-- SELECT * FROM unnested_changed_records
-- UNION ALL
-- SELECT * FROM new_records

-- Creating a graph data model

-- INSERT INTO edges
-- WITH deduped AS (
-- 	SELECT
-- 		*,
-- 		ROW_NUMBER() OVER (PARTITION BY player_id, game_id) AS row_num
-- 	FROM game_details
-- )
-- SELECT
-- 	player_id AS subject

-- SELECT DISTINCT edge_type FROM edges
-- INSERT INTO edges
-- WITH deduped AS (
-- 	SELECT
-- 		*,
-- 		ROW_NUMBER() OVER (PARTITION BY player_id, game_id) AS row_num
-- 	FROM game_details
-- ),
-- filtered AS (
-- 	SELECT * 
-- 	FROM deduped 
-- 	WHERE row_num = 1
-- ),
-- aggregated AS (
-- 	SELECT
-- 		f1.player_id AS subject_player_id,
-- 		f2.player_id AS object_player_id,
-- 		CASE
-- 			WHEN f1.team_abbreviation = f2.team_abbreviation THEN 'shares_team'::edge_type
-- 			ELSE 'plays_against'::edge_type
-- 		END AS edge_type,
-- 		MAX(f1.player_name) AS subject_player_name,
-- 		MAX(f2.player_name) AS object_player_name,
-- 		COUNT(1) AS num_games,
-- 		SUM(f1.pts) AS subject_points,
-- 		SUM(f2.pts) AS object_points
-- 	FROM filtered f1
-- 	JOIN filtered f2
-- 		ON f1.game_id = f2.game_id
-- 		AND f1.player_name <> f2.player_name
-- 	WHERE f1.player_id > f2.player_id
-- 	GROUP BY
-- 		f1.player_id,
-- 		f2.player_id,
-- 		CASE
-- 			WHEN f1.team_abbreviation = f2.team_abbreviation THEN 'shares_team'::edge_type
-- 			ELSE 'plays_against'::edge_type
-- 		END
-- )
-- SELECT
-- 	subject_player_id AS subject_identifier,
-- 	'player'::vertex_type AS subject_type,
-- 	object_player_id AS object_identifier,
-- 	'player'::vertex_type AS object_type,
-- 	edge_type,
-- 	json_build_object(
-- 		'num_games', num_games,
-- 		'subject_points', subject_points,
-- 		'object_points', object_points
-- 	)
-- FROM aggregated

-- SELECT
-- 	*
-- FROM vertices v
-- JOIN edges e
-- 	ON ((v.identifier = e.subject_identifier) OR (v.identifier = e.object_identifier))
-- 	AND ((v.type = e.subject_type) OR (v.type = e.object_type))
-- WHERE identifier = '1626174'

-- SELECT subject_type, object_type, edge_type FROM edges GROUP BY 1,2,3